name = "lyriverse-brain"
main = "scripts/worker-index.js"
compatibility_date = "2024-03-01"

[triggers]
crons = ["0 */6 * * *"] # Every 6 hours

[[kv_namespaces]]
binding = "LYRI_DATA"
id = "842b3198708345ac830baacd839b0a09" # Placeholder ID, usually set during deployment

# No production sub-env needed for this simple setup
